services:

  api:
    build: ./api_nginx
    container_name: spring-api
    environment:
      - DB_HOST=${DB_HOST}       
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    expose:
      - "8080"
    networks:
      - shared_net  

networks:
  shared_net:       
    external: true